#!/bin/sh
: 'Copyright (C) 2023 TecnoDespegue'
#!/bin/bash

# @Bourne_Again
# wget is.gd/arcris && sh arcris
# https://is.gd/stats.php?url=arcris

clear
pacman -Sy --noconfirm
pacman -Sy 
clear

pacmaninit1=$( pacman -Ss glibc  | grep "glibc" 	| grep "installed" | wc -l )
pacmaninit2=$( pacman -Ss dialog | grep "dialog" 	| grep "installed" | wc -l )
pacmaninit3=$( pacman -Ss curl 	 | grep "curl" 		| grep "installed" | wc -l )

if [[ "$pacmaninit1" = "1" && "$pacmaninit2" = "1" && "$pacmaninit3" = "1" ]] ; then
clear
else
clear
sudo pacman -Sy glibc dialog curl ncurses --noconfirm --needed
sleep 5
fi

clear
curl -LJO https://github.com/RDesign-Castex/TecnoArch.git
tar  -xvf  RDesign-Castex/TecnoArch.git
cd tecnoarch

cp .dialogrc /root
chmod +x *
clear
echo "Cargando..."
sleep 2
sh tecnoarch-install
